const novelData = [
    {
        id:1,
        name:"เกียร์วุ่นรัก",
        author:"a",
        category:"kide",
        imgUrl:"เกียร์วุ่นรัก.jpeg"
    },
    {
        id:2,
        name:"ชายาเคียงหทัย",
        author:"b",
        category:"kide",
        imgUrl:"ชายาเคียงหทัย.jpeg"
    },
    {
        id:3,
        name:"เซียนหมอซ้อนกล",
        author:"c",
        category:"kide",
        imgUrl:"เซียนหมอซ้อนกล.jpeg"
    },
    {
        id:4,
        name:"ตัวแทนของท่านอ๋อง",
        author:"d",
        category:"kide",
        imgUrl:"ตัวแทนของท่านอ๋อง.jpeg"
    },
    {
        id:5,
        name:"นางมาร",
        author:"e",
        category:"kide",
        imgUrl:"นางมาร.jpeg"
    },
    {
        id:6,
        name:"มหาเศรษฐีของโลกคือผมเอง",
        author:"f",
        category:"kide",
        imgUrl:"มหาเศรษฐีของโลกคือผมเอง.png"
    },
]

module.exports = novelData